# Generated by Django 6.0.7 on 2026-07-21 14:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompaniment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Accompagnement',
                'verbose_name_plural': 'Accompagnements',
            },
        ),
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='boissons/')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Boisson',
                'verbose_name_plural': 'Boissons',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('max_included_accompaniments', models.PositiveSmallIntegerField(default=0, help_text="Nombre d'accompagnements inclus gratuitement dans le prix du plat")),
                ('availability_mode', models.CharField(choices=[('always', 'Toujours disponible'), ('specific_days', 'Jours spécifiques'), ('sold_out', 'Épuisé')], default='always', max_length=20)),
                ('available_days', models.CharField(blank=True, help_text='Ex : Lundi,Mardi,Mercredi — utilisé si availability_mode = specific_days', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('accompaniments', models.ManyToManyField(blank=True, help_text='Accompagnements proposables pour ce plat', related_name='meals', to='meal.accompaniment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meal.category')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire')], default='cash', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.client')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text="Prix du plat au moment de la commande (indépendant d'un futur changement de prix)", max_digits=8)),
                ('extra_accompaniments_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accompaniments', models.ManyToManyField(blank=True, help_text='Accompagnements choisis par le client, parmi ceux du plat', related_name='order_items', to='meal.accompaniment')),
                ('boisson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='meal.boisson')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='meal.meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal.order')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='meal.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
