# Generated by Django 6.0.7 on 2026-07-23 15:32

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='available_days',
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], help_text='Jour de la semaine', max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver ce jour rendra indisponible tout son menu.')),
                ('meals', models.ManyToManyField(blank=True, help_text='Plats disponibles ce jour-là', related_name='daily_menus', to='meal.meal')),
            ],
            options={
                'verbose_name': 'Menu Journalier',
                'verbose_name_plural': 'Menus Journaliers',
            },
        ),
    ]
