# Generated by Django 6.0.7 on 2026-07-27 01:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_remove_meal_available_days_dailymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='boisson',
        ),
        migrations.CreateModel(
            name='OrderItemAccompaniment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('accompaniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.accompaniment')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_accompaniments', to='meal.orderitem')),
            ],
            options={
                'verbose_name': 'Accompagnement de commande',
                'verbose_name_plural': 'Accompagnements de commande',
                'unique_together': {('order_item', 'accompaniment')},
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='accompaniments',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accompaniments',
            field=models.ManyToManyField(blank=True, help_text='Accompagnements choisis par le client avec leur quantité', related_name='order_items', through='meal.OrderItemAccompaniment', to='meal.accompaniment'),
        ),
        migrations.CreateModel(
            name='OrderItemBoisson',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.boisson')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_boissons', to='meal.orderitem')),
            ],
            options={
                'verbose_name': 'Boisson de commande',
                'verbose_name_plural': 'Boissons de commande',
                'unique_together': {('order_item', 'boisson')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='boissons',
            field=models.ManyToManyField(blank=True, help_text='Boissons choisies par le client avec leur quantité', related_name='order_items', through='meal.OrderItemBoisson', to='meal.boisson'),
        ),
    ]
