# Generated by Django 6.0.7 on 2026-07-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_remove_orderitem_boisson_orderitemaccompaniment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='meal.meal'),
        ),
    ]
