# Generated by Django 6.0.7 on 2026-07-31 11:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_orderitem_meal'),
        ('users', '0009_alter_companysetting_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('description', models.TextField(help_text='Description du plat souhaité, allergies, etc.')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Nombre de portions')),
                ('target_date', models.DateField(blank=True, help_text='Date souhaitée', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('priced', 'Tarif proposé'), ('accepted', 'Acceptée et ajoutée au panier'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix proposé par l'administrateur", max_digits=10, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du refus éventuel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to='users.client')),
                ('linked_meal', models.ForeignKey(blank=True, help_text='Plat généré automatiquement une fois le tarif validé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_requests', to='meal.meal')),
            ],
            options={
                'verbose_name': 'Demande sur mesure',
                'verbose_name_plural': 'Demandes sur mesure',
                'ordering': ['-created'],
            },
        ),
    ]
