# Generated by Django 6.0.7 on 2026-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_customorderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_loyalty_gift',
            field=models.BooleanField(default=False, help_text='Indique si cette commande inclut un cadeau de fidélité à livrer.'),
        ),
    ]
