# Generated by Django 6.0.7 on 2026-07-24 10:13

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message_attachment_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-created'],
            },
        ),
    ]
