# Generated by Django 6.0.7 on 2026-07-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_orderitem_meal'),
        ('users', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Commande concernée par ce message (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='meal.order'),
        ),
    ]
