# Generated by Django 6.0.7 on 2026-07-29 14:19

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique.', primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Suppression logique (soft delete).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles au format JSON.')),
                ('restaurant_name', models.CharField(default="Mam's", max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('navbar_image', models.ImageField(blank=True, null=True, upload_to='company/navbar/')),
                ('slogan', models.TextField(blank=True)),
                ('address', models.CharField(default='Bafoussam, Cameroun', max_length=255)),
                ('phone', models.CharField(default='+237', max_length=50)),
                ('email', models.EmailField(default='contact@mams.cm', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('monday_friday', models.CharField(default='10h – 22h', max_length=100)),
                ('saturday', models.CharField(default='10h – 23h', max_length=100)),
                ('sunday', models.CharField(default='11h – 21h', max_length=100)),
                ('copyright_text', models.CharField(default="© 2026 Les délices de Mam's. Tous droits réservés.", max_length=255)),
                ('footer_note', models.CharField(default='Fait avec ♥ à Bafoussam', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
