# Generated by Django 6.0.7 on 2026-07-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_order'),
        ('users', '0007_companysetting'),
    ]

    operations = [
    ]
