# Generated by Django 6.0.7 on 2026-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0006_message_order_0007_companysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='address',
            field=models.CharField(default='Bafoussam, Cameroun', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='copyright_text',
            field=models.CharField(default="© 2026 Les délices de Mam's. Tous droits réservés.", max_length=120),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='footer_note',
            field=models.CharField(default='Fait avec ♥ à Bafoussam', max_length=80),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='monday_friday',
            field=models.CharField(default='10h – 22h', max_length=30),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='phone',
            field=models.CharField(default='+237', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='restaurant_name',
            field=models.CharField(default="Mam's", help_text='20 caractères maximum', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='saturday',
            field=models.CharField(default='10h – 23h', max_length=30),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='slogan',
            field=models.CharField(blank=True, help_text='80 caractères maximum', max_length=80),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='sunday',
            field=models.CharField(default='11h – 21h', max_length=30),
        ),
    ]
