# Generated by Django 6.0.7 on 2026-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_companysetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Points de fidélité (1 commande = 10 pts)'),
        ),
    ]
