# Generated by Django 6.0.7 on 2026-09-10 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_registrationotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registrationotp',
            new_name='users_regis_email_2d8f2d_idx',
            old_name='users_registrat_email_purpose_idx',
        ),
        migrations.RenameIndex(
            model_name='registrationotp',
            new_name='users_regis_expires_23954c_idx',
            old_name='users_registrat_expires_at_idx',
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique pour la vérification OTP.', primary_key=True, serialize=False, unique=True),
        ),
    ]
